#!/bin/sh

./../lorax -a < helloworld_sprint.lrx
# ./../lorax -a < functest.lrx
# ./../lorax -a < ../dfs.lrx
# ./../lorax -a < ../gcd.lrx
# ./../lorax -a < ../helloworld.lrx
# ./../lorax -a < experimental.lrx
# ./../lorax -a < ../parserkitchensink.lrx

# currently not testing any tree accessor operationsgit 